#[build]
#target = "riscv64gc-unknown-linux-gnu"

#[target.riscv64gc-unknown-linux-gnu]
#linker = "riscv64gc-unknown-linux-gnu-gcc"
[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -nographic -bios none -kernel"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
]
